services:
  k8s-web:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ~/.kube:/root/.kube:ro
      - ~/.minikube:/root/.minikube:ro   # ✅ << เพิ่มบรรทัดนี้
    environment:
      - KUBECONFIG=/root/.kube/config
